# Site settings
title: QLearning Robocode
email: krrisgit@gmail.com
description: "Robocode robot which uses Reinforcement Learning algorithm (QLearning)."
baseurl: ""
url: "http://krris.github.io/QLearning-Robocode/"

# Build settings
markdown: kramdown
permalink: pretty
